[package]
name = "logger"
version = "0.1.0"
edition = "2021"

# Build a library
[lib]
name = "logger"
path = "src/lib.rs"

# Build a binary as a test/demo
[[bin]]
name = "logger_test"
path = "src/main.rs"

[dependencies]
chrono = "0.4"
lazy_static = "1.4"
